source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DataVisualization_Example' do
  pod "DataVisualization", :path => "../"
end

target 'DataVisualization_Tests' do
  pod "DataVisualization", :path => "../"

  pod 'Quick'
  pod 'Nimble'
#  pod 'FBSnapshotTestCase'
#  pod 'Nimble-Snapshots'

  pod 'RxSwift'
  pod 'RxCocoa'
end
